CREATE CACHED TABLE PUBLIC.USER(
  LOGIN VARCHAR(255) NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UNIQUE_LOGIN PRIMARY KEY(LOGIN);
