CREATE CACHED TABLE PUBLIC.USER(
  LOGIN VARCHAR(255) NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UNIQUE_LOGIN PRIMARY KEY(LOGIN);

insert into user values ('admin',true,'$2a$04$Uyub1RLGeJY1TTbJlFHEf.DywgMac99XD9dle/WDm7eHBXRpaFI.q','ROLE_ADMIN','Administrator')